### ISSUE TITLE
"This linter plugin for SublimeLinter provides an interface to yamllint." links to self

### ISSUE THREAD

**Issue by FichteFoll** [thomasmeeus/SublimeLinter-contrib-yamllint#1]
The section in the readme stating

> This linter plugin for SublimeLinter provides an interface to yamllint.

links to this repository, not the upstream one for yamllint.

**Comment by ghost** [comment]
I see a handful of "yamllint" repos on GitHub. Anyone know exactly to which this repo should refer?

**Comment by ghost** [comment]
I think it's supposed to be linked thusly - https://github.com/thomasmeeus/SublimeLinter-contrib-yamllint/pull/3
