### ISSUE TITLE
Installation impossible

### ISSUE THREAD

**Issue by marksaitis** [thomasmeeus/SublimeLinter-contrib-yamllint#18]
Mac M3 sonoma, brew
Installation impossible.
Brew installs python, pip3 installs yamllint
The rest does not work. Can't locate the thing and further install instructions look complex.
I appreciate the open software, but if we have ability in sulbime editor to install plugins - it should be all possible through there. Or whatever guide needs to be followed should be more simple, a list of WORKING commands in the plugins readme which is displayed, scenario for multiple platforms. As now you go to one page, another page, and nothing works and it ends up a waste of time.

**Comment by thomasmeeus** [comment]
Hi,
This plugin hooks into Sublimelinter which again uses plugins to accomplish the linting. 
The issue you describe is not related to this plugin specifically, but how Sublimelinter needs to be installed/configured. 
Only thing I can do is refer you to the docs of sublimelinter: https://www.sublimelinter.com/en/master/
The initial setup of Sublimelinter is indeed a bit tedious, however once configured it allows you easily install multiple linting plugins.
