### ISSUE TITLE
yamllint deactivated, no available version of python or yamllint satisfies yamllint@python3

### ISSUE THREAD

**Issue by jsf5** [thomasmeeus/SublimeLinter-contrib-yamllint#2]
What version of Python 3 does SublimeLinter-contrib-yamllint require to function?

I have Python 3.6 installed and yamllint version 1.10.0. yamllint.exe can be found in my path (i.e., `where yamllint` returns `C:\Python36\Scripts\yamllint.exe`), but I get the following error when SubmlimeText 3 starts and YAML linting does not work.

It appears to have found both my Python 3.6 installation *and* the yamllint.exe executable but, for some reason, believes they do not satisfy their version requirements.

Thanks!

> SublimeLinter: yamllint imported <module 'yamllint' from 'C:\\Python36\\lib\\site-packages\\yamllint\\__init__.py'> 
> SublimeLinter: find_python(version='3', script='yamllint', module=<module 'yamllint' from 'C:\\Python36\\lib\\site-packages\\yamllint\\__init__.py'>) 
> **SublimeLinter: find_python: requested version = {'major': 3, 'minor': None}**
> SublimeLinter: find_python: available version = {'major': 3, 'minor': 3} 
> SublimeLinter: find_python: <= ('<builtin>', None, 3, 3) 
> SublimeLinter: find_python(version='3', script='yamllint', module=None) 
> SublimeLinter: find_python: requested version = {'major': 3, 'minor': None} 
> SublimeLinter: find_python: system python = C:\Python36\python.exe 
> SublimeLinter: find_python: available version = {'major': 3, 'minor': 6} 
> SublimeLinter: find_python: 'yamllint' path = C:\Python36\Scripts\yamllint.exe 
> SublimeLinter: find_python: <= ('C:\\Python36\\Scripts\\yamllint.exe', None, 3, 6) 
> **SublimeLinter: WARNING: yamllint deactivated, no available version of python or yamllint satisfies yamllint@python3**

**Comment by thomasmeeus** [comment]
Hi,

my plugin uses https://github.com/adrienverge/yamllint to lint yaml files. Please check their installation procedure. I'm also not familiar with Windows, so I can't help with that unfortunately. I'm currently using yamllint 1.9.0 & Python 3.6 on mac without issues.
