### ISSUE TITLE
Only lints on save?

### ISSUE THREAD

**Issue by jagibson** [thomasmeeus/SublimeLinter-contrib-yamllint#4]
Hi - nice plugin! 

I'm not sure if this is a bug or not, but sublimelinter-contrib-yamllint will only lint for me when I save a file or open an an existing file that has errors.  That is - if I make changes to a file that passes tests when I open it yamllint will not show me linting errors until I save the file.  Previously I was using SublimeLinter-pyyaml which linted in real-time.  Is this be design?  Is there a way to force it to lint without saving the file first (shortcut key or something)?  

Thank you

**Comment by thomasmeeus** [comment]
Hi,

for me it's sufficient that it lints on save, because I auto-save my files after each modification.
I haven't looked into adding this feature yet. I'm kind of busy right now, but I'll add it to my to do list. It would be a nice improvement.

**Comment by josephchelad** [comment]
Hello Thomas,

I've created a PR that should enable background linting. Do check it out when you're free. :)
https://github.com/thomasmeeus/SublimeLinter-contrib-yamllint/pull/5

**Comment by thomasmeeus** [comment]
Merged
