### ISSUE TITLE
Depreciations since sulimelinter 4.0

### ISSUE THREAD

**Issue by jtisserand** [thomasmeeus/SublimeLinter-contrib-yamllint#6]
Messages in sublime text console:

- The '@python' in 'yamllint@python3' has been deprecated and no effect anymore. You can safely remove it.

- yamllint: Defining 'cls.syntax' has been deprecated. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector

**Comment by thomasmeeus** [comment]
Hi,

both are fixed in https://github.com/thomasmeeus/SublimeLinter-contrib-yamllint/releases/tag/1.0.2
