### ISSUE TITLE
What version of python to use

### ISSUE THREAD

**Issue by 211217613** [thomasmeeus/SublimeLinter-contrib-yamllint#8]
Just for clarification, you should add what version of python to use for installing the dependencies.

I don't know if this is obvious or not for other users but do we `pip install yamllint` using python2 or python3 or does it not matter?

**Comment by thomasmeeus** [comment]
Hi,

Yamllint is just a dependency of this plug-in. Please have a look at their install guide. I’ve used python2 in the past, but switched to python3 about half a year ago. I didn’t encounter any issues as the functionality of the app remains the same.
