### ISSUE TITLE
installing yamllint from apt repo

### ISSUE THREAD

**Issue by 211217613** [thomasmeeus/SublimeLinter-contrib-yamllint#9]
Is it [not]recommended to install yamllint using apt ??

**Comment by thomasmeeus** [comment]
Hi,

That’s fully up to you. I’m using pip on python3, but any other package manager can work fine as long as the binairy is present in your $PATH

**Comment by 211217613** [comment]
I think I asked this because sublime was having trouble finding the yaml command. The obvious thing to do was to install via `sudo apt install yaml`.
